name: Build, test and package OpenUI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  PACKAGE_NAME: openui-${{ github.sha }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史用于版本信息

      # 安装 pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/pnpm-lock.yaml
          node-version: 20
          cache: "pnpm"

      # 前端构建流程
      - name: Build frontend
        working-directory: ./frontend
        run: |
          pnpm install
          pnpm run build

      # 创建代码压缩包（排除 Docker 相关文件）
      - name: Create code archive
        run: |
          # 复制 LICENSE 文件到打包目录
          mkdir -p package-dist
          cp LICENSE package-dist/
          
          # 复制前端构建产物
          cp -r frontend/dist package-dist/frontend
          
          # 复制后端代码（排除 Docker 相关文件）
          rsync -av --exclude='Dockerfile*' --exclude='docker-compose*' backend/ package-dist/backend
          
          # 创建压缩包
          tar -czvf ${{ env.PACKAGE_NAME }}.tar.gz package-dist
          
      # 上传制品
      - name: Upload code package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_NAME }}.tar.gz

  create-release:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download code package
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}

      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.SHORT_SHA }}
          tag_name: ${{ env}}